### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by maximoortelli** [maximoortelli/Ruby-Capstone-Group#29]
[GitHub Link to Capstone Project](https://github.com/maximoortelli/Ruby-Capstone-Group/projects/1)

There are 2 members on our team:

- Team member 1 - @maximoortelli 
- Team member 2 - @fmanimashaun

**Comment by HAMMAS-SALEEM** [comment]
# Required Changes :recycle:
![Ukhv](https://user-images.githubusercontent.com/93039359/247195854-e274f284-2e3a-423b-8939-7e4efb638ee0.gif)

## Hey @maximoortelli, @fmanimashaun :wave:

## Highlights :1st_place_medal:

✔️ Descriptive Issue Title
✔️ Descriptive Issue Summary
✔️ Using Github Project Feature
✔️ Following some requirements

Good job on implementing some of the requirements, There are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

# Required Changes ♻️

| ## 1. |
|-|
| ![image](https://github.com/maximoortelli/Ruby-Capstone-Group/assets/93039359/348020e0-d8ce-43cc-8237-efdc78ed7e93) |

- [x] It would be nice if you have a card for this requirement because i don't see it anywhere in your Kanban Board so kindly make this card to follow the project requirements 👍 and keep track of your project steps 😊

| ## 2. |
|-|
| ![image](https://github.com/maximoortelli/Ruby-Capstone-Group/assets/93039359/de6a9a0c-9860-4879-b4a8-5d751d16d8d9) |

- [x] It would be nice if these cards equally assigned to both members to follow the project requirements 👍

**Comment by maximoortelli** [comment]
This is the url of the letter that I needed to implement to meet all the requirements. 

- https://github.com/maximoortelli/Ruby-Capstone-Group/issues/30

We have already dealt the cards, thank you for your time and your great review 👍😃

**Comment by rloterh** [comment]
## Status: Approved :heavy_check_mark:

Hi Team,  

Your **Ruby group capstone** board is ready! 🍾🍾 Congratulations!  🎉💯🌟 

## Highlights 🎯
🎲 Cards created for required tasks!
🎲 Fairly distributed tasks!

Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
